version: 2.0
jobs:
    
    "all-jupyter-py36-cu90_all-jupyter-py36_all-jupyter":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-jupyter-py36-cu90 -t $DOCKER_REPO:all-jupyter-py36 -t $DOCKER_REPO:all-jupyter -f docker/Dockerfile.all-jupyter-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-jupyter-py36-cu90            
            - run: docker push $DOCKER_REPO:all-jupyter-py36            
            - run: docker push $DOCKER_REPO:all-jupyter
    
    "tensorflow-py36-cpu_tensorflow-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:tensorflow-py36-cpu -t $DOCKER_REPO:tensorflow-cpu -f docker/Dockerfile.tensorflow-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:tensorflow-py36-cpu            
            - run: docker push $DOCKER_REPO:tensorflow-cpu
    
    "keras-py36-cu90_keras-py36_keras":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:keras-py36-cu90 -t $DOCKER_REPO:keras-py36 -t $DOCKER_REPO:keras -f docker/Dockerfile.keras-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:keras-py36-cu90            
            - run: docker push $DOCKER_REPO:keras-py36            
            - run: docker push $DOCKER_REPO:keras
    
    "all-py36-cpu_all-cpu_py36-cpu_cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-py36-cpu -t $DOCKER_REPO:all-cpu -t $DOCKER_REPO:py36-cpu -t $DOCKER_REPO:cpu -f docker/Dockerfile.all-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-py36-cpu            
            - run: docker push $DOCKER_REPO:all-cpu            
            - run: docker push $DOCKER_REPO:py36-cpu            
            - run: docker push $DOCKER_REPO:cpu
    
    "keras-py36-cpu_keras-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:keras-py36-cpu -t $DOCKER_REPO:keras-cpu -f docker/Dockerfile.keras-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:keras-py36-cpu            
            - run: docker push $DOCKER_REPO:keras-cpu
    
    "all-jupyter-py36-cpu_all-jupyter-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-jupyter-py36-cpu -t $DOCKER_REPO:all-jupyter-cpu -f docker/Dockerfile.all-jupyter-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-jupyter-py36-cpu            
            - run: docker push $DOCKER_REPO:all-jupyter-cpu
    
    "pytorch-py36-cu90_pytorch-py36_pytorch":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:pytorch-py36-cu90 -t $DOCKER_REPO:pytorch-py36 -t $DOCKER_REPO:pytorch -f docker/Dockerfile.pytorch-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:pytorch-py36-cu90            
            - run: docker push $DOCKER_REPO:pytorch-py36            
            - run: docker push $DOCKER_REPO:pytorch
    
    "all-py36-cu90_all-py36_all_py36-cu90_latest":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-py36-cu90 -t $DOCKER_REPO:all-py36 -t $DOCKER_REPO:all -t $DOCKER_REPO:py36-cu90 -t $DOCKER_REPO:latest -f docker/Dockerfile.all-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-py36-cu90            
            - run: docker push $DOCKER_REPO:all-py36            
            - run: docker push $DOCKER_REPO:all            
            - run: docker push $DOCKER_REPO:py36-cu90            
            - run: docker push $DOCKER_REPO:latest
    
    "tensorflow-py36-cu90_tensorflow-py36_tensorflow":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:tensorflow-py36-cu90 -t $DOCKER_REPO:tensorflow-py36 -t $DOCKER_REPO:tensorflow -f docker/Dockerfile.tensorflow-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:tensorflow-py36-cu90            
            - run: docker push $DOCKER_REPO:tensorflow-py36            
            - run: docker push $DOCKER_REPO:tensorflow
    
    "pytorch-py36-cpu_pytorch-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:pytorch-py36-cpu -t $DOCKER_REPO:pytorch-cpu -f docker/Dockerfile.pytorch-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:pytorch-py36-cpu            
            - run: docker push $DOCKER_REPO:pytorch-cpu

workflows:
    version: 2
    build:
        jobs:
            - "all-jupyter-py36-cu90_all-jupyter-py36_all-jupyter"
            - "tensorflow-py36-cpu_tensorflow-cpu"
            - "keras-py36-cu90_keras-py36_keras"
            - "all-py36-cpu_all-cpu_py36-cpu_cpu"
            - "keras-py36-cpu_keras-cpu"
            - "all-jupyter-py36-cpu_all-jupyter-cpu"
            - "pytorch-py36-cu90_pytorch-py36_pytorch"
            - "all-py36-cu90_all-py36_all_py36-cu90_latest"
            - "tensorflow-py36-cu90_tensorflow-py36_tensorflow"
            - "pytorch-py36-cpu_pytorch-cpu"